export const siteConfig = {
  description:
    'A React docs site showing how reveal-ui keeps summary and workflow context visible while richer detail opens inline for editors, plan comparison, and nested choice flows.',
  discussionUrl: 'https://github.com/HackEAC/reveal-ui/discussions',
  installCommand: 'npm install reveal-ui motion react react-dom',
  keywords: [
    'reveal-ui',
    'persistent-summary disclosure',
    'inline reveal editor',
    'expanding card disclosure',
    'React UI primitive',
    'headless React component',
    'design system primitive',
    'React select alternative',
    'nested modal alternative',
    'accordion alternative',
    'plan comparison UI',
    'nested edit flow',
    'property chooser UI',
    'rich option picker',
    'dialog inline chooser',
    'replace select with inline reveal',
  ],
  name: 'reveal-ui',
  repoUrl: 'https://github.com/HackEAC/reveal-ui',
  title: 'reveal-ui | Persistent-summary disclosure for React',
  url: 'https://hackeac.github.io/reveal-ui',
}
